variant = 82
isu = 503266
week = "четная"

[[tuesday.events]]
type = "Практика"
subject = "Алгебра и алгоритмы"
teacher = "Рыбкин Никита Геннадьевич"
room = "2316"
address = "Кронверкский пр., д.49, лит.А"
start = "08:10"
end = "09:40"
mode = "очно"

[[tuesday.events]]
type = "Практика"
subject = "Математический анализ"
teacher = "Романова Екатерина Владимировна"
room = "2330"
address = "Кронверкский пр., д.49, лит.А"
start = "09:50"
end = "11:20"
mode = "очно"

[[tuesday.events]]
type = "Лекция"
subject = "Математический анализ"
teacher = "Романова Екатерина Владимировна"
room = "1405"
address = "Кронверкский пр., д.49, лит.А"
start = "11:30"
end = "13:00"
mode = "очно"

[[tuesday.events]]
type = "Лекция"
subject = "Алгебра и алгоритмы"
teacher = "Попов Антон Игоревич"
room = "1405"
address = "Кронверкский пр., д.49, лит.А"
start = "13:30"
end = "15:00"
mode = "очно"

[[thursday.events]]
type = "Практика"
subject = "Социальная история России"
teacher = "Кудина Юлия Игоревна"
room = "1410"
address = "Кронверкский пр., д.49, лит.А"
start = "11:30"
end = "13:00"
mode = "очно"

[[thursday.events]]
type = "Лекция"
subject = "Социальная история России"
teacher = "Сосницкий Дмитрий Александрович"
room = "Alfa Space (2304)"
address = "Кронверкский пр., д.49, лит.А"
start = "13:30"
end = "15:00"
mode = "очно"